import { useMemo, useState } from "react";
import "../styles/components/analisis.css";
const f=v=>v?new Date(Number(v)).toLocaleString("es-PE",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}):"—";
const n=v=>String(v||"").padStart(2,"0");
export default function Analisis({salas=[],salaCodigo="",historial=[]}){
 const [sala,setSala]=useState(salaCodigo||"todas"),[modo,setModo]=useState("maquinas"),[detalle,setDetalle]=useState(null),[tab,setTab]=useState("motivos");
 const logs=useMemo(()=>historial.filter(x=>sala==="todas"||x.sala===sala),[historial,sala]);
 const machines=useMemo(()=>{const m={};logs.forEach(x=>{const k=(x.sala||"")+":"+n(x.machine);m[k]??={key:k,sala:x.sala,machine:n(x.machine),items:[],first:Infinity,last:0};m[k].items.push(x);m[k].first=Math.min(m[k].first,Number(x.inicio||x.id||Infinity));m[k].last=Math.max(m[k].last,Number(x.fin||x.inicio||x.id||0))});return Object.values(m)},[logs]);
 const reasons=useMemo(()=>{const m={};logs.forEach(x=>{const k=x.motivo||x.reason||"—";m[k]??={key:k,name:x.reason||x.nombre||k,items:[],first:Infinity,last:0};m[k].items.push(x);m[k].first=Math.min(m[k].first,Number(x.inicio||x.id||Infinity));m[k].last=Math.max(m[k].last,Number(x.fin||x.inicio||x.id||0))});return Object.values(m)},[logs]);
 const info=x=>{const s=salas.find(q=>q.codigo===x.sala),m=(s?.maquinas||[]).find(q=>n(q.numero)===n(x.machine));return{s,m}};
 return <section className="analysis-page"><div className="analysis-controls"><select value={sala} onChange={e=>setSala(e.target.value)} aria-label="Sala"><option value="todas">Todas las salas</option>{salas.map(x=><option key={x.codigo} value={x.codigo}>{x.nombre}</option>)}</select><div className="analysis-switch"><button className={modo==="maquinas"?"is-on":""} onClick={()=>setModo("maquinas")}>Máquinas</button><button className={modo==="motivos"?"is-on":""} onClick={()=>setModo("motivos")}>Motivos</button></div></div><div className="sheet analysis-table"><table><thead><tr>{modo==="maquinas"?<><th>Máquina</th><th>Primer registro</th><th>Último registro</th><th>Paros</th></>:<><th>Motivo</th><th>Primer paro</th><th>Último paro</th><th>Paros</th></>}</tr></thead><tbody>{modo==="maquinas"?machines.map(x=>{const z=info(x),live=x.items.some(i=>!i.fin&&i.status!=="atendido");return <tr key={x.key} onClick={()=>setDetalle(x)}><td><strong>{x.machine}</strong> {z.m?.marca||z.m?.nombre||""}{z.m?.modelo?" · "+z.m.modelo:""}</td><td>{f(x.first)}</td><td className={live?"is-live":""}>{f(x.last)}</td><td>{x.items.length}</td></tr>}):reasons.map(x=><tr key={x.key}><td><strong>{x.key}</strong> {x.name!==x.key?x.name:""}</td><td>{f(x.first)}</td><td>{f(x.last)}</td><td>{x.items.length}</td></tr>)}</tbody></table>{!logs.length?<p className="analysis-empty">No hay historial real para esta selección.</p>:null}</div>{detalle?<div className="analysis-layer" onClick={e=>{if(e.target===e.currentTarget)setDetalle(null)}}><aside className="analysis-drawer"><header><h2>Máquina</h2><button className="icon-btn" onClick={()=>setDetalle(null)}>×</button></header><div className="analysis-machine"><strong>{detalle.machine}</strong><div><span>{info(detalle).m?.marca||"—"}</span><span>{info(detalle).m?.modelo||"—"}</span><span>{info(detalle).m?.serie||"—"}</span></div></div><div className="analysis-tabs"><button className={tab==="motivos"?"is-on":""} onClick={()=>setTab("motivos")}>Motivos</button><button className={tab==="paros"?"is-on":""} onClick={()=>setTab("paros")}>Paros</button></div><div className="analysis-detail">{tab==="motivos"?Object.values(detalle.items.reduce((o,x)=>{const k=x.motivo||x.reason||"—";o[k]??={name:x.reason||x.nombre||k,count:0};o[k].count++;return o},{})).map(x=><div key={x.name}><span>{x.name}</span><strong>{x.count}</strong></div>):[...detalle.items].sort((x,y)=>Number(y.inicio)-Number(x.inicio)).map((x,i)=><div key={x.id||i}><span>{x.reason||x.nombre||x.motivo||"Paro"}</span><time>{f(x.inicio)}</time></div>)}</div><footer>Última actualización: {f(detalle.last)}</footer></aside></div>:null}</section>
}